import Lists from "@/components/Lists";
import Navbar from "@/components/Navbar";
import ToTopButton from "@/components/ToTopButton";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Lists />
        {children}
        <ToTopButton />
      </body>
    </html>
  );
}
